name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-latex-base
          pip install -r requirements.txt
          make
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
