name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-glx xvfb -y
          export DISPLAY=:99.0
          export PYVISTA_OFF_SCREEN=True
          which Xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
          set +x
          sudo apt-get install -y --no-install-recommends texlive-latex-base texlive-latex-extra
          pip install -r requirements.txt
          make
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
